[mob]
identifier = "MOSQUITO"
name = "mosquito"

[description]
day = "A hungry mosquito!"

[attributes]
vision = 1
taste = 1
smell = 1
hearing = 1
touch = 1
strength = 1
speed = 1
agility = 1
stamina = 1
weight = 1
height = 1
memory = 1
analysis = 1
emotions = 1
focus = 1
magic = 1

[[attacks]]
name = "bite"
type = "piercing"
damage = "1"
